# Generated by Django 4.1.7 on 2023-04-10 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Mobileno', models.BigIntegerField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studentmarksapp.city')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studentmarksapp.course')),
            ],
        ),
    ]
